/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns server status and version (not versioned)
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Exchange a refresh token for a new access/refresh token pair.
         *     Send the refresh token in the Authorization header.
         *     Commercial edition only.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes/unsynced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get unsynced notes
         * @description Returns notes that have not yet been synced to Obsidian
         */
        get: operations["getUnsyncedNotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get note by ID
         * @description Returns a single note by its UUID
         */
        get: operations["getNote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes/mark-synced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark notes as synced
         * @description Mark notes as synced after plugin writes them to Obsidian
         */
        post: operations["markNotesSynced"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plugin initialization
         * @description Called once when plugin connects for the first time.
         *     Saves categories from plugin and processes any pending notes
         *     (messages sent before plugin was configured) in background.
         */
        post: operations["pluginInit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all categories
         * @description Returns all categories for plugin sync
         */
        get: operations["getCategories"];
        /**
         * Update categories
         * @description Replace all categories with new list from plugin
         */
        put: operations["updateCategories"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tags registry
         * @description Returns tags registry with usage counts per category
         */
        get: operations["getTags"];
        /**
         * Update tags registry
         * @description Replace tags registry with new data from plugin
         */
        put: operations["updateTags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user settings
         * @description Returns current user settings including data retention period.
         */
        get: operations["getUserSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update user settings
         * @description Update user settings. Currently supports data_retention_days (0-7).
         *     0 = delete notes immediately after sync.
         *     1-7 = delete notes N days after sync.
         */
        patch: operations["updateUserSettings"];
        trace?: never;
    };
    "/v1/user/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export all user data
         * @description GDPR Art. 20 — Data Portability. Returns all user data as JSON.
         *     Commercial edition only.
         */
        get: operations["exportUserData"];
        put?: never;
        post?: never;
        /**
         * Delete all user data
         * @description GDPR Art. 17 — Right to Erasure. Permanently deletes all user data.
         *     Commercial edition only.
         */
        delete: operations["deleteUserData"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active sessions
         * @description Returns all active (non-revoked) sessions for the authenticated user.
         *     Commercial edition only.
         */
        get: operations["listUserSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example 0.1.0 */
            version: string;
        };
        NoteResponse: {
            /** @description Note UUID (as string) */
            id: string;
            /** @description Note name (used as Obsidian filename) */
            name: string;
            /** @description Raw transcript content */
            content: string;
            /** @description Note category (e.g., "work", "personal") */
            category: string;
            /** @description List of tags */
            tags: string[];
            /** @description AI-generated summary */
            summary: string;
            /**
             * Format: date-time
             * @description Creation timestamp (ISO 8601)
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Sync timestamp (null if not synced)
             */
            synced_at?: string | null;
            /**
             * @description Vault file path to append to (when this note is a reply/addition
             *     to an already-synced note). Null for standalone notes.
             */
            append_to?: string | null;
        };
        SyncResponse: {
            notes: components["schemas"]["NoteResponse"][];
            /**
             * Format: date-time
             * @description Current server time (ISO 8601)
             */
            server_time: string;
        };
        MarkSyncedRequest: {
            /** @description List of note UUIDs to mark as synced (as strings) */
            note_ids: string[];
            /** @description Mapping of note UUID to vault file path: {note_id: path} */
            vault_paths?: {
                [key: string]: string;
            };
        };
        MarkSyncedResponse: {
            /** @description Number of notes successfully marked as synced */
            synced_count: number;
        };
        CategoryItem: {
            /** @description Category name (e.g., "work", "work/meetings") */
            name: string;
            /** @description Human-readable category description */
            description: string;
        };
        CategoriesResponse: {
            categories: components["schemas"]["CategoryItem"][];
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        CategoriesUpdateRequest: {
            categories: components["schemas"]["CategoryItem"][];
        };
        TagsRegistryResponse: {
            /**
             * @description Tags registry: {category: {tag: count}}
             * @example {
             *       "work": {
             *         "meeting": 12,
             *         "planning": 5
             *       },
             *       "personal": {
             *         "health": 3
             *       }
             *     }
             */
            registry: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        TagsUpdateRequest: {
            /** @description Tags registry: {category: {tag: count}} */
            registry: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        UserSettingsResponse: {
            /**
             * @description Days to keep synced notes on server before automatic deletion.
             *     0 = delete immediately after sync. Default: 7.
             * @example 7
             */
            data_retention_days: number;
        };
        UserSettingsUpdateRequest: {
            /**
             * @description Days to keep synced notes on server before automatic deletion.
             *     0 = delete immediately after sync.
             */
            data_retention_days?: number;
        };
        ErrorResponse: {
            /** @description Error message */
            detail: string;
        };
        TokenPairResponse: {
            /** @description Short-lived JWT access token */
            access_token: string;
            /** @description Long-lived JWT refresh token */
            refresh_token: string;
            /**
             * Format: date-time
             * @description Access token expiration (ISO 8601)
             */
            expires_at: string;
        };
        SessionInfo: {
            /** Format: uuid */
            id: string;
            device_name: string | null;
            device_type: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at: string;
            /** @description Whether this is the session making the request */
            is_current: boolean;
        };
        UserSessionsResponse: {
            sessions: components["schemas"]["SessionInfo"][];
        };
        UserDataExport: {
            user: {
                /** Format: uuid */
                id?: string;
                chat_id?: number;
                email?: string | null;
                locale?: string | null;
                /** Format: date-time */
                gdpr_consent_at?: string | null;
                gdpr_consent_version?: string | null;
                /** Format: date-time */
                created_at?: string;
            };
            notes: components["schemas"]["NoteResponse"][];
            sessions: {
                /** Format: uuid */
                id?: string;
                device_name?: string | null;
                device_type?: string | null;
                /** Format: date-time */
                created_at?: string;
                /** Format: date-time */
                last_used_at?: string;
            }[];
            audit_log: {
                action?: string;
                resource_type?: string | null;
                resource_id?: string | null;
                /** Format: date-time */
                created_at?: string;
            }[];
            /** Format: date-time */
            exported_at: string;
        };
        UserDataDeleteResponse: {
            deleted: boolean;
            notes_deleted: number;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Missing, expired, or invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Session revoked or user not found */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUnsyncedNotes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of unsynced notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
    getNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Note UUID */
                noteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Invalid note ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markNotesSynced: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkSyncedRequest"];
            };
        };
        responses: {
            /** @description Notes marked as synced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkSyncedResponse"];
                };
            };
        };
    };
    pluginInit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriesUpdateRequest"];
            };
        };
        responses: {
            /** @description Plugin initialized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                        categories_saved: number;
                        pending_notes: number;
                        message: string;
                    };
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
        };
    };
    updateCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriesUpdateRequest"];
            };
        };
        responses: {
            /** @description Categories updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
        };
    };
    getTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsRegistryResponse"];
                };
            };
        };
    };
    updateTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsUpdateRequest"];
            };
        };
        responses: {
            /** @description Tags registry updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsRegistryResponse"];
                };
            };
        };
    };
    getUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUserSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportUserData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full user data export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDataExport"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteUserData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Data deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDataDeleteResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUserSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSessionsResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
