/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns server status and version (not versioned)
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes/unsynced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get unsynced notes
         * @description Returns notes that have not yet been synced to Obsidian
         */
        get: operations["getUnsyncedNotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get note by ID
         * @description Returns a single note by its UUID
         */
        get: operations["getNote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes/mark-synced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark notes as synced
         * @description Mark notes as synced after plugin writes them to Obsidian
         */
        post: operations["markNotesSynced"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all categories
         * @description Returns all categories for plugin sync
         */
        get: operations["getCategories"];
        /**
         * Update categories
         * @description Replace all categories with new list from plugin
         */
        put: operations["updateCategories"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tags registry
         * @description Returns tags registry with usage counts per category
         */
        get: operations["getTags"];
        /**
         * Update tags registry
         * @description Replace tags registry with new data from plugin
         */
        put: operations["updateTags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example 0.1.0 */
            version: string;
        };
        NoteResponse: {
            /** @description Note UUID (as string) */
            id: string;
            /** @description Note name (used as Obsidian filename) */
            name: string;
            /** @description Raw transcript content */
            content: string;
            /** @description Note category (e.g., "work", "personal") */
            category: string;
            /** @description List of tags */
            tags: string[];
            /** @description AI-generated summary */
            summary: string;
            /**
             * Format: date-time
             * @description Creation timestamp (ISO 8601)
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Sync timestamp (null if not synced)
             */
            synced_at?: string | null;
        };
        SyncResponse: {
            notes: components["schemas"]["NoteResponse"][];
            /**
             * Format: date-time
             * @description Current server time (ISO 8601)
             */
            server_time: string;
        };
        MarkSyncedRequest: {
            /** @description List of note UUIDs to mark as synced (as strings) */
            note_ids: string[];
        };
        MarkSyncedResponse: {
            /** @description Number of notes successfully marked as synced */
            synced_count: number;
        };
        CategoryItem: {
            /** @description Category name (e.g., "work", "work/meetings") */
            name: string;
            /** @description Human-readable category description */
            description: string;
        };
        CategoriesResponse: {
            categories: components["schemas"]["CategoryItem"][];
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        CategoriesUpdateRequest: {
            categories: components["schemas"]["CategoryItem"][];
        };
        TagsRegistryResponse: {
            /**
             * @description Tags registry: {category: {tag: count}}
             * @example {
             *       "work": {
             *         "meeting": 12,
             *         "planning": 5
             *       },
             *       "personal": {
             *         "health": 3
             *       }
             *     }
             */
            registry: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        TagsUpdateRequest: {
            /** @description Tags registry: {category: {tag: count}} */
            registry: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getUnsyncedNotes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of unsynced notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
    getNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Note UUID */
                noteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Invalid note ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markNotesSynced: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkSyncedRequest"];
            };
        };
        responses: {
            /** @description Notes marked as synced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkSyncedResponse"];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
        };
    };
    updateCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriesUpdateRequest"];
            };
        };
        responses: {
            /** @description Categories updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
        };
    };
    getTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsRegistryResponse"];
                };
            };
        };
    };
    updateTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsUpdateRequest"];
            };
        };
        responses: {
            /** @description Tags registry updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagsRegistryResponse"];
                };
            };
        };
    };
}
